### ISSUE TITLE
Installing word2vec on python3.4 doesn't work

### ISSUE THREAD

**Issue by cozos** [danielfrg/word2vec#19]
Hey,

I tried to install word2vec on python3.4 and got the following:

```
      File "/tmp/pip-build-9693mw7d/word2vec/setup.py", line 29
        print ' '.join(command)
                ^
    SyntaxError: invalid syntax
```

I looked into your `setup.py` and it seems like you already fixed the python3 compatibility, but I think you didn't upload the release to pip. I cloned the repo and installed the local package and it works, but just FYI.

Thanks,

Arwin

**Comment by bobcyw** [comment]
try this one: pip install git+https://github.com/danielfrg/word2vec

**Comment by AkshatM** [comment]
Stack trace of suggested fix from @bobcyw 

```
$ pip install git+https://github.com/danielfrg/word2vec

Collecting git+https://github.com/danielfrg/word2vec
  Cloning https://github.com/danielfrg/word2vec to c:\users\akshat\appdata\local
\temp\pip-hw2jj5cs-build
    Complete output from command python setup.py egg_info:
    gcc word2vec-c\word2vec.c -o bin\word2vec -lm -pthread -O3 -Wall -march=nati
ve -funroll-loops -Wno-unused-result
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\akshat\AppData\Local\Temp\pip-hw2jj5cs-build\setup.py", lin
e 37, in <module>
        compile('word2vec.c', 'word2vec')
      File "C:\Users\akshat\AppData\Local\Temp\pip-hw2jj5cs-build\setup.py", lin
e 32, in compile
        return_code = subprocess.call(command)
      File "C:\Python34\lib\subprocess.py", line 537, in call
        with Popen(*popenargs, **kwargs) as p:
      File "C:\Python34\lib\subprocess.py", line 859, in __init__
        restore_signals, start_new_session)
      File "C:\Python34\lib\subprocess.py", line 1112, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified

    ----------------------------------------
←[31mCommand "python setup.py egg_info" failed with error code 1 in C:\Users\aks
hat\AppData\Local\Temp\pip-hw2jj5cs-build←[0m
```

Clearly a better solution is needed. Please fix.

**Comment by danielfrg** [comment]
Just uploaded version 0.8 to pypi and it should work with python 3. Let me know if it doesnt.

Thanks!
