### ISSUE TITLE
Error  Can't import word2vec 

### ISSUE THREAD

**Issue by Rahulvks** [danielfrg/word2vec#29]
When importing Word2vec in python 2.7 am facing error kindly anyone help

```
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import word2vec
  File "word2vec.py", line 14, in <module>
    model = word2vec.Word2Vec(sentences, size=100, window=4, min_count=1, workers=4)
  File "/usr/local/lib/python2.7/dist-packages/gensim-0.12.3-py2.7-linux-x86_64.egg/gensim/models/word2vec.py", line 432, in __init__
    self.train(sentences)
  File "/usr/local/lib/python2.7/dist-packages/gensim-0.12.3-py2.7-linux-x86_64.egg/gensim/models/word2vec.py", line 690, in train
    raise RuntimeError("you must first build vocabulary before training the model")
RuntimeError: you must first build vocabulary before training the model
```

**Comment by danielfrg** [comment]
The error is not related to the library, you have a file called `word2vec.py` in the same directory as the python file that you are executing so when you do `import word2vec` is importing your file instead of the library.

**Comment by Rahulvks** [comment]
hi danielfrg

Error installing word2vec

1.svn checkout http://word2vec.googlecode.com/svn/trunk/
 Checked out revision 42. 
 cd trunk/
 make
 make: Nothing to be done for `all'
 cant do make,tried make all,make file

**Comment by danielfrg** [comment]
I don't maintain the original SVN repo.
