### ISSUE TITLE
Word2vec import error iun python 

### ISSUE THREAD

**Issue by Rahulvks** [danielfrg/word2vec#30]
Kindly help me to correct this error

```
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import word2vec
  File "word2vec.py", line 14, in <module>
    model = word2vec.Word2Vec(sentences, size=100, window=4, min_count=1, workers=4)
  File "/usr/local/lib/python2.7/dist-packages/gensim-0.12.3-py2.7-linux-x86_64.egg/gensim/models/word2vec.py", line 432, in __init__
    self.train(sentences)
  File "/usr/local/lib/python2.7/dist-packages/gensim-0.12.3-py2.7-linux-x86_64.egg/gensim/models/word2vec.py", line 690, in train
    raise RuntimeError("you must first build vocabulary before training the model")
RuntimeError: you must first build vocabulary before training the model
```

**Comment by danielfrg** [comment]
Same as https://github.com/danielfrg/word2vec/issues/30 :)
