### ISSUE TITLE
Encoding issues when attempting to load word2vec models

### ISSUE THREAD

**Issue by grantdelozier** [danielfrg/word2vec#33]
Hello,

I'm attempting to load a word2vec model pre-trained on the Google News corpora, but get encoding issues

```
import word2vec

model = word2vec.load('/Users/grant/Downloads/GoogleNews-vectors-negative300.bin', kind='bin')

Traceback (most recent call last):
  File "w2v_exps.py", line 3, in <module>
    model = word2vec.load('/Users/grant/Downloads/GoogleNews-vectors-negative300.bin', kind='bin')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/word2vec/io.py", line 18, in load
    return word2vec.WordVectors.from_binary(fname, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/word2vec/wordvectors.py", line 171, in from_binary
    vocab[i] = word.decode(encoding)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 0: invalid start byte
```

I assume that the pre-trained google news vectors found at https://code.google.com/p/word2vec/ would be utf-8 encoded, but I guess not? Is this project not intended to work with those files?

**Comment by danielfrg** [comment]
If I remember correctly those files are not `utf-8` encoded, they are `ISO-8859-1` [1]. There is an `encoding` kwarg in `from_binary` and `from_text` with a default of `utf-8`, try changing that.

[1] https://code.google.com/p/word2vec/issues/detail?id=19&can=1&q=encoding

**Comment by grantdelozier** [comment]
Specifying the encoding option to ISO-8859-1 fixed the issue. Thanks!

**Comment by adelabdelli** [comment]
@danielfrg  i'm working on arabic documents which are encoded in UTF-8, so how can i load the model with utf-8 ? ( i get the same error, how can i fix it ?)
