### ISSUE TITLE
unable to install word2vec on linux

### ISSUE THREAD

**Issue by sharadlnx** [danielfrg/word2vec#34]
I have installed Cython before installing word2vec
numpy version 1.10.4
gcc 4.8.4
 
This is the problem which i get during installation of word2vec
```
$ sudo pip install word2vec 
[sudo] password for sharad: 
The directory '/home/sharad/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/sharad/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting word2vec
  Downloading word2vec-0.9.0.tar.gz (49kB)
    100% |████████████████████████████████| 53kB 5.3kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-qm2BCb/word2vec/setup.py", line 101, in <module>
        ext_modules=cythonize("word2vec/word2vec_noop.pyx"),
      File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 758, in cythonize
        aliases=aliases)
      File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 651, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 103, in nonempty
        raise ValueError(error_msg)
    ValueError: 'word2vec/word2vec_noop.pyx' doesn't match any files
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-qm2BCb/word2vec
```
kindly provide me the solution
Thanks

**Comment by rionbr** [comment]
Until this bug is not fixed:
On linux you can install word2vec straight of the [google project page](https://code.google.com/archive/p/word2vec/). If you need a python wrapper, just download this current version and use on the same directory as your code. It works then! =]

**Comment by danielfrg** [comment]
Sorry about this. It was a missing file in the `tar` file. It should be fixed on `0.9.1`. Try:
`pip install -U word2vec`.

**Comment by rionbr** [comment]
Works like a charm! Thanks!
btw: for most people the requirements (numpy and cython) should be already installed, so just `pip install word2vec` should suffice.

**Comment by danielfrg** [comment]
Thanks for testing :)
