### ISSUE TITLE
Failing  to load GoogleNews-vectors-negative300.bin

### ISSUE THREAD

**Issue by a-shkarupin** [danielfrg/word2vec#54]
Hello, 
while trying to load the pre-trained model from google news dataset, I'm getting the following error (both python3 and python2):

```
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import word2vec
>>> word2vec.load('GoogleNews-vectors-negative300.bin')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/venvs/word2vec_python2/local/lib/python2.7/site-packages/word2vec/io.py", line 18, in load
    return word2vec.WordVectors.from_binary(fname, *args, **kwargs)
  File "~/venvs/word2vec_python2/local/lib/python2.7/site-packages/word2vec/wordvectors.py", line 202, in from_binary
    vocab[i] = word.decode(encoding)
  File "~/venvs/word2vec_python2/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 0: invalid start byte

```
The error looks very similar to https://github.com/danielfrg/word2vec/issues/51

**Comment by danielfrg** [comment]
Those files are not `utf-8` encoded, they are `ISO-8859-1` encoded so do:

```python
model = word2vec.load('/Users/drodriguez/Downloads/GoogleNews-vectors-negative300.bin', encoding="ISO-8859-1")
```

**Comment by jplehmann** [comment]
FYI, I had to add the `new_lines` arg: https://github.com/danielfrg/word2vec/issues/58#issuecomment-466043696
