### ISSUE TITLE
unable to install word2vec on Ubuntu 18.04.1

### ISSUE THREAD

**Issue by ftk1000** [danielfrg/word2vec#61]
Tried to **install word2vec** with and without '-U' flag, with pip and pip3. Keep receiving the same error:
```
$ pip install word2vec
Collecting word2vec
  Using cached https://files.pythonhosted.org/packages/98/9c/0cc6019be231950235517c29d2d6a2fca76dfa75ad4162ccce22fb1b4364/word2vec-0.9.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zG4Ed2/word2vec/setup.py", line 23, in <module>
        from Cython.Build import cythonize
    ImportError: No module named Cython.Build
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zG4Ed2/word2vec/
```

Environment:
```
$ uname -a
Linux E7440 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ python --version
Python 2.7.15+

$ python3 --version
Python 3.6.8
```

**Comment by danielfrg** [comment]
You need to install Cython first.

```
pip install cython
```

will fix it.
