### ISSUE TITLE
Dependency on Cython

### ISSUE THREAD

**Issue by sakurai-youhei** [danielfrg/word2vec#63]
In relation to https://github.com/danielfrg/word2vec/issues/61, installation seems to depend on Cython now.

**How to reproduce the issue**

1. Spin up clean environment by docker - `docker run -it python:3 bash`.
2. Run `pip install word2vec` according to README.

**Expected behavior**

The installation of word2vec should succeed.

**Actual behavior**

The installation of word2vec fails due to missing Cython which is referred in setup.py.

```
root@586fc4889a4a:/# pip install word2vec
Collecting word2vec
  Downloading https://files.pythonhosted.org/packages/ce/51/5e2782b204015c8aef0ac830297c2f2735143ec90f592b9b3b909bb89757/word2vec-0.10.2.tar.gz (60kB)
     |████████████████████████████████| 61kB 38kB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8jl_l2_x/word2vec/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8jl_l2_x/word2vec/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-8jl_l2_x/word2vec/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8jl_l2_x/word2vec/setup.py", line 4, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by danielfrg** [comment]
Documented the dependency on #64
